apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /{{ .Chart.Name }}
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.app.ports.http }}